### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by wilfried18** [jtbuaa/easyhome#12]
It is a shame not to be able to add or remove icons (I speak of the browser, sms, call
otherwise why not the ability to choose an icon theme (with all that there is the "play store"

**Comment by jtbuaa** [comment]
thank you for report this issue. but I have no plan to maintain this project. you can fix it by yourself if you like. thanks.

**Comment by wilfried18** [comment]
thank you for the proposal but that will not be possible not I devs
